apiVersion: v1
kind: ConfigMap
metadata:
  name: kwok-provider-config
  namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: autoscaler-kwok
    meta.helm.sh/release-namespace: default
data:
  config: |-
    apiVersion: v1alpha1
    kwok: {}
    readNodesFrom: configmap
    configmap:
      name: kwok-provider-templates
    nodes:
    nodegroups:
      fromNodeLabelKey: "kwok-nodegroup"
