apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"monitoring.coreos.com/v1","kind":"Prometheus","metadata":{"annotations":{"meta.helm.sh/release-name":"my-prometheus","meta.helm.sh/release-namespace":"monitoring"},"labels":{"app":"kube-prometheus-stack-prometheus","app.kubernetes.io/instance":"my-prometheus","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/part-of":"kube-prometheus-stack","app.kubernetes.io/version":"65.3.2","chart":"kube-prometheus-stack-65.3.2","heritage":"Helm","release":"my-prometheus"},"name":"my-prometheus-kube-prometh-prometheus","namespace":"monitoring"},"spec":{"alerting":{"alertmanagers":[{"apiVersion":"v2","name":"my-prometheus-kube-prometh-alertmanager","namespace":"monitoring","pathPrefix":"/","port":"http-web"}]},"automountServiceAccountToken":true,"enableAdminAPI":false,"evaluationInterval":"30s","externalUrl":"http://my-prometheus-kube-prometh-prometheus.monitoring:9090","hostNetwork":false,"image":"quay.io/prometheus/prometheus:v2.54.1","listenLocal":false,"logFormat":"logfmt","logLevel":"info","paused":false,"podMonitorNamespaceSelector":{},"podMonitorSelector":{"matchLabels":{"release":"my-prometheus"}},"portName":"http-web","probeNamespaceSelector":{},"probeSelector":{"matchLabels":{"release":"my-prometheus"}},"replicas":1,"retention":"10d","routePrefix":"/","ruleNamespaceSelector":{},"ruleSelector":{"matchLabels":{"release":"my-prometheus"}},"scrapeConfigNamespaceSelector":{},"scrapeConfigSelector":{"matchLabels":{"release":"my-prometheus"}},"scrapeInterval":"30s","securityContext":{"fsGroup":2000,"runAsGroup":2000,"runAsNonRoot":true,"runAsUser":1000,"seccompProfile":{"type":"RuntimeDefault"}},"serviceAccountName":"my-prometheus-kube-prometh-prometheus","serviceMonitorNamespaceSelector":{},"serviceMonitorSelector":{},"shards":1,"tsdb":{"outOfOrderTimeWindow":"0s"},"version":"v2.54.1","walCompression":true}}
    meta.helm.sh/release-name: my-prometheus
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2024-11-13T12:10:52Z"
  generation: 4
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: my-prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 65.3.2
    chart: kube-prometheus-stack-65.3.2
    heritage: Helm
    release: my-prometheus
  name: my-prometheus-kube-prometh-prometheus
  namespace: monitoring
  resourceVersion: "7587"
  uid: 8e514e32-cbf9-4629-a59a-bc3ca3fe415b
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - prometheus
            - key: prometheus
              operator: In
              values:
              - my-prometheus-kube-prometh-prometheus
          topologyKey: kubernetes.io/hostname
        weight: 100
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: my-prometheus-kube-prometh-alertmanager
      namespace: monitoring
      pathPrefix: /
      port: http-web
  automountServiceAccountToken: true
  enableAdminAPI: false
  evaluationInterval: 30s
  externalUrl: http://my-prometheus-kube-prometh-prometheus.monitoring:9090
  hostNetwork: false
  image: quay.io/prometheus/prometheus:v2.54.1
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: my-prometheus
  portName: http-web
  probeNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: my-prometheus
  replicas: 1
  retention: 10d
  routePrefix: /
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      release: my-prometheus
  scrapeConfigNamespaceSelector: {}
  scrapeConfigSelector:
    matchLabels:
      release: my-prometheus
  scrapeInterval: 30s
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  serviceAccountName: my-prometheus-kube-prometh-prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  shards: 1
  tsdb:
    outOfOrderTimeWindow: 0s
  version: v2.54.1
  walCompression: true
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-11-13T12:26:57Z"
    message: ""
    observedGeneration: 4
    reason: ""
    status: "True"
    type: Available
  - lastTransitionTime: "2024-11-13T12:26:57Z"
    message: ""
    observedGeneration: 4
    reason: ""
    status: "True"
    type: Reconciled
  paused: false
  replicas: 1
  selector: app.kubernetes.io/instance=my-prometheus-kube-prometh-prometheus,app.kubernetes.io/managed-by=prometheus-operator,app.kubernetes.io/name=prometheus,operator.prometheus.io/name=my-prometheus-kube-prometh-prometheus,prometheus=my-prometheus-kube-prometh-prometheus
  shardStatuses:
  - availableReplicas: 1
    replicas: 1
    shardID: "0"
    unavailableReplicas: 0
    updatedReplicas: 1
  shards: 1
  unavailableReplicas: 0
  updatedReplicas: 1
