apiVersion: apps/v1
kind: Deployment
metadata:
  name: dual-container-app-v2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dual-container-v2
  template:
    metadata:
      labels:
        app: dual-container-v2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - kwok
      tolerations:
      - key: "kwok.x-k8s.io/node"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: app-container
        image: nginx
      - name: sidecar-container
        image: busybox
        command: ["sleep", "infinity"]