apiVersion: v1
kind: Node
metadata:
  name: kwok-node-0
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    kwok.x-k8s.io/node: fake
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/os: linux
    kubernetes.io/hostname: kwok-node-0
    kubernetes.io/role: agent
    node-role.kubernetes.io/agent: ""
    type: kwok
spec:
  taints:
    - key: kwok.x-k8s.io/node
      value: fake
      effect: NoSchedule
status:
  capacity:
    cpu: "10"
    memory: "10Gi"
    pods: "110"
  allocatable:
    cpu: "10"
    memory: "10Gi"
    pods: "110"
  nodeInfo:
    architecture: amd64
    kubeletVersion: fake
    kubeProxyVersion: fake
    operatingSystem: linux