apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kwok-controller
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: kwok-controller
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
    - port: http
      path: /metrics/nodes/kwok-node-0/metrics/resource
      interval: 15s