apiVersion: v1
kind: Node
metadata:
  annotations:
    kwok.x-k8s.io/node: fake
  labels:
    node.kubernetes.io/instance-type: c5d.9xlarge
    topology.kubernetes.io/zone: us-west-1a
    type: virtual
  name: fake-node-1
spec:
  taints:
  - effect: NoSchedule
    key: kwok-provider
    value: "true"
status:
  allocatable:
    cpu: 35
    ephemeral-storage: 900Gi
    memory: 71Gi
    pods: 110
  capacity:
    cpu: 36
    ephemeral-storage: 900Gi
    memory: 72Gi
    pods: 110

