apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ${CLUSTER_NAME}
  region: us-east-1

iam:
  serviceRoleARN: arn:aws:iam::463020534911:role/eksctl-costplanner-cluster-ServiceRole-1QUD8QENCHW88

iamIdentityMappings:
  - arn: arn:aws:iam::463020534911:role/AWSReservedSSO_SWE_05aa46cf18f9af02
    username: admin-user1
    groups:
      - system:masters
    noDuplicateARNs: true

vpc:
  id: vpc-608da31a
  sharedNodeSecurityGroup: sg-deb051f6
  subnets:
    private:
      us-east-1d: { id: subnet-27d4cc09 }
      us-east-1f: { id: subnet-f0a770fe }

addons:
  - name: aws-ebs-csi-driver
  - name: coredns
  - name: kube-proxy
  - name: vpc-cni

