apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  schedulerName: custom-scheduler  # Specifies the custom scheduler
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80

